# 
# @brief    : custom mavlink msg, message id="152" name="FIXED_TARGET_POSITION_P2M"
# @time     : 2018/09/13
# @auhtor   : liuxu <liuxu.ccc@gmail.com> 
#

#fixed box positions that would be goten before takeoff by GPS (GCS->Pix->Mavros)

float32 box1_x
float32 box1_y
float32 box1_z 

float32 box2_x   
float32 box2_y   
float32 box2_z 

float32 box3_x  
float32 box3_y  
float32 box3_z  

float32 box4_x  
float32 box4_y  
float32 box4_z 

float32 box5_x  
float32 box5_y  
float32 box5_z 

float32 box6_x  
float32 box6_y  
float32 box6_z 